services:
  db:
    image: postgres:latest
    ports:
      - '5432:5432'
    volumes:
      - db-data:/var/lib/postgresql/data

  api:
    image: ${API_IMAGE:-pern_app_api:api_latest}
    build:
      context: ./api
      dockerfile: ${DOCKERFILE_API:-Docker/production/Dockerfile}
    ports:
      - '3001:3001'
    environment:
      NODE_ENV: ${NODE_ENV:-development}
      DB_HOST: db
      DB_DBNAME: todo_db
      DB_USERNAME: postgres
      DB_PASSWORD: password
    depends_on:
      - db

  client:
    image: ${CLIENT_IMAGE:-pern_app_client:client_latest}
    build:
      context: ./client
      dockerfile: ${DOCKERFILE_CLIENT:-Docker/production/Dockerfile}
    ports:
      - '5173:5173'
    environment:
      NODE_ENV: ${NODE_ENV:-development}
    depends_on:
      - api

volumes:
  db-data:
