services:
  db:
    image: postgres:latest
    ports:
      - '5432:5432'
    volumes:
      - db-data:/var/lib/postgresql/data

  api:
    build:
      context: ./api
      dockerfile: ${DOCKERFILE_API}
    image: pern_app:api_latest
    ports:
      - '3001:3001'
    environment:
      NODE_ENV: ${NODE_ENV}
      DB_HOST: db
      DB_DBNAME: todo_db
      DB_USERNAME: postgres
      DB_PASSWORD: password
    depends_on:
      - db

  client:
    build:
      context: ./client
      dockerfile: ${DOCKERFILE_CLIENT}
    image: pern_app:client_latest
    ports:
      - '5173:5173'
    environment:
      NODE_ENV: ${NODE_ENV}
    depends_on:
      - api

volumes:
  db-data:
