name: CI/CD

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.TOKEN_CD }}

      - name: Build and push production Docker images
        run: |
          export DOCKERFILE_API=Docker/production/Dockerfile
          export DOCKERFILE_CLIENT=Docker/production/Dockerfile
          export NODE_ENV=production
          docker-compose build
          docker tag pern_app ghcr.io/${{ github.repository }}:api_latest
          docker push ghcr.io/${{ github.repository }}:api_latest
          docker tag pern_app ghcr.io/${{ github.repository }}:client_latest
          docker push ghcr.io/${{ github.repository }}:client_latest

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Pull production images and deploy
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          eval $(ssh-agent -s)
          ssh-add ~/.ssh/id_rsa
          ssh -o StrictHostKeyChecking=no ${{ secrets.USER }} "
            docker login ghcr.io -u ${{ github.actor }} -p ${{ secrets.TOKEN_CD }}
            docker pull ghcr.io/${{ github.repository }}:api_latest
            docker pull ghcr.io/${{ github.repository }}:client_latest
            docker run -d --name api -p 3001:3001 ghcr.io/${{ github.repository }}:api_latest
            docker run -d --name client -p 5173:5173 ghcr.io/${{ github.repository }}:client_latest
          "

        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          SSH_KNOWN_HOSTS: ${{ secrets.SSH_KNOWN_HOSTS }}
          DOCKERFILE_API: Docker.production.Dockerfile
          DOCKERFILE_CLIENT: Docker.production.Dockerfile
          NODE_ENV: production
