name: CI/CD

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.TOKEN_CD }}

      - name: Build and push production Docker image
        run: |
          export DOCKERFILE_API=api.Docker.production.Dockerfile
          export DOCKERFILE_CLIENT=client.Docker.production.Dockerfile
          export NODE_ENV=production
          docker-compose build
          docker tag myapp ghcr.io/${{ github.repository }}:latest
          docker push ghcr.io/${{ github.repository }}:latest


  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.TOKEN_CD }}

      - name: Pull production image and deploy
        run: |
          ssh ${{ secrets.USER }} "
            docker pull ghcr.io/${{ github.repository }}:latest
            docker-compose -f /path/to/docker-compose.yml up -d
          "
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          SSH_KNOWN_HOSTS: ${{ secrets.SSH_KNOWN_HOSTS }}
          DOCKERFILE_API: api.Docker.production.Dockerfile
          DOCKERFILE_CLIENT: client.Docker.production.Dockerfile
          NODE_ENV: production
